### ISSUE TITLE
Невозможно дополнить функционал

### ISSUE THREAD

**Issue by pavlm** [yii2mod/yii2-image#1]
Для простых случаев компонент работает, за это спасибо, но есть следующие сложности.
Большинство методов компонента объявлены private и невозможно к ним обратиться из производного класса.
Также жестко закодирован экшен обработчика.
Планируется что-то в данном направлении? Или может быть есть какие-то альтернативы?

**Comment by ihorchepurnyi** [comment]
Здравствуйте, сейчас честно говоря очень сложно найти время чтобы обновить этот пакет, если у вас есть возможность, создайте пожалуйста пулл реквест, я бы посоветовал вам использовать следующией пакет - https://github.com/yii2tech/ar-file

**Comment by ihorchepurnyi** [comment]
На этой недели постараюсь немного оптимизировать этот пакет

**Comment by pavlm** [comment]
Спасибо за наводку, но не очень понравилось в том пакете смешение ответственностей, он и загружает и ресайзит. Думаю у вашего компонента подход более удачный, возможно сделаю PR.

**Comment by ihorchepurnyi** [comment]
окей, большое спасибо!
